dryRun: true

repoLabels:
  - name: bug
    description: Something isn't working
    color: ee1111

  - name: documentation
    description: Improvements or additions to the documentation
    color: 0e8a16

  - name: Refactor
    description: Refactor code
    color: 531ae7
