# ============================================
#                   LABEL-SYNC
# --------------------------------------------
# GitHub Action to manage labels declaratively
# ============================================

name: Label Sync

# Activation Events
# =================

on:
  # When .github/labels.yml changes are pushed to the default branch
  push:
    paths:
      - .github/labels.yml

  # When a label webhook event (create, update, delete) is triggered
  label:

  # When a workflow event is dispatched manually
  workflow_dispatch:

# Jobs
# ====

jobs:
  label-sync:
    runs-on: ubuntu-latest
    name: Label Sync
    steps:
      # Actions/Checkout
      # ================

      - name: Checkout
        uses: actions/checkout@v3

      # Execute label-sync action
      # =========================

      - name: label-sync
        uses: Shresht7/label-sync-action@main
        id: label-sync
        with:
          dryrun: false # Will not make any actual changes if true (default: true)
          create: true # If true, label-sync has permissions to create labels (default: true)
          update: true # If true, label-sync has permissions to update labels (default: true)
          delete: false # If true, label-sync has permissions to delete labels (default: false)
        env:
          # Needed to make use of the GitHub API to modify labels and update .github/labels.yml file
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create Pull-Request with updated Label Config
      # =============================================

      - name: update-labels-config
        id: update-labels-config
        uses: peter-evans/create-pull-request@v4.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "label-sync"
          commit-message: "Update labels 🏷"
          title: "Update labels 🏷"
