# ============================================
#                   LABEL-SYNC
# --------------------------------------------
# GitHub Action to manage labels declaratively
# ============================================

name: label-sync

# Activation Events
# =================

on:
  push:
    paths:
      - .github/labels.yaml # When .github/labels.yaml changes are pushed to the default branch
  label:  # When a label webhook event (create, update, delete) is triggered
  workflow_dispatch:  # When a workflow event is dispatched manually

# Jobs
# ====

jobs:
  label-sync:
    runs-on: ubuntu-latest
    
    name: label-sync
    steps:
    
      # Actions/Checkout
      # ================

      # Required for GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      # Execute label-sync Action
      # ========================

      - name: label-sync
        uses: Shresht7/label-sync-action@main
        id: label-sync

        # Config Parameters
        # -----------------

        with:
          commit-message: Update labels 🏷 # The commit message when label-sync updates .github/labels.yaml file in the repo (default: label-sync Update)
          dryrun: true    # Will not make any actual changes if true (default: true)
          create: true    # If true, label-sync has permissions to create labels (default: true)
          update: true    # If true, label-sync has permissions to update labels (default: true)
          delete: false   # If true, label-sync has permissions to delete labels (default: false)

        # Environment Variables
        # ---------------------

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to make use of the GitHub API to modify labels and update .github/labels.yaml file
