# ==============
# BUILD AND TEST
# ==============

name: Build-Test

# Activation Events
# =================

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

# Jobs
# ====

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run build

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          commitmessage: Update labels 🏷 # The commit message when label-sync updates .github/labels.yaml file in the repo (default: label-sync Update)
          dryrun: true    # Will not make any actual changes if true (default: true)
          create: true    # If true, label-sync has permissions to create labels (default: true)
          update: true    # If true, label-sync has permissions to update labels (default: true)
          delete: false   # If true, label-sync has permissions to delete labels (default: false)